app/accounts/urls.py
from django.urls import path
from app.accounts import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signin/', views.LoginView.as_view(), name='signin'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

app/blog/urls.py
from django.urls import path
from app.blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blogs'),
    path('<uuid:id>', views.BlogDetailView.as_view(), name='blogs_detail')
]

app/home/urls.py
from django.urls import path
from app.home import views

app_name = "home"
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutUsView.as_view(), name='about'),
    path('mentor/', views.MentorsView.as_view(), name='mentor'),
    path('mentor/<uuid:id>', views.MentorDetailView.as_view(), name='mentor_detail'),
    path('contact/', views.ContactUsView.as_view(), name='contact'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.home.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('auth/', include('app.accounts.urls')),
    path('blog/', include('app.blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/base/models.py
from django.db import models

import uuid 

class BaseModel(models.Model):
    id = models.UUIDField( 
         primary_key = True, 
         default = uuid.uuid4, 
         editable = False)
    create_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

    class Meta: 
        abstract = True

app/blog/models.py
from django.db import models
from app.base.models import BaseModel
from app.accounts.models import User
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

BLOG_STTYLE = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
)


class BlogCategories(BaseModel):
    name = models.CharField(max_length = 255, null=True, blank = True)
    
    def __str__(self):
        return self.name
    
class BlogTags(BaseModel):
    name = models.CharField(max_length = 255, null=True, blank = True)
    
    def __str__(self):
        return self.name
    
    
class Blog(BaseModel):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length = 255, null=True, blank = True)
    body = RichTextUploadingField()
    photo1 =  models.ImageField(upload_to='blog/')
    photo2 =  models.ImageField(upload_to='blog/')
    category = models.ForeignKey(BlogCategories, on_delete=models.SET_NULL, null=True, blank=True)
    tag = models.ManyToManyField(BlogTags, blank=True)
    style = models.CharField(max_length = 1, null=True, blank = True, choices = BLOG_STTYLE)
    
    def __str__(self):
        return f"{self.user.first_name} - {self.title}"

class BlogComment(BaseModel):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, blank=True, related_name='commint')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='commint')
    comment = models.TextField(null=True, blank = True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE, blank=True, null=True, related_name='children')
    
    def __str__(self):
        return f'{self.user.first_name} - {self.comment}'

app/base/views.py
from django.shortcuts import render

# Create your views here.

app/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Blog, BlogCategories, BlogTags, BlogComment
from django.core.paginator import Paginator
from hitcount.views import HitCountDetailView

# Create your views here.


class BlogView(View):
    def get(self, request, *args, **kwargs):
        
        blog = Blog.objects.all()
        
        page_size = request.GET.get('page_size', 12)
        paginator = Paginator(blog, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        
        context = {
            'blog' : page_obj
        }
        return render(request, 'blogs.html', context)
    
    
class BlogDetailView(HitCountDetailView):
    count_hit = True
    def get(self, request, id, *args, **kwargs):
        category = BlogCategories.objects.all()
        tags = BlogTags.objects.all()
        blog = get_object_or_404(Blog, id=id)
        last_blog = Blog.objects.all().order_by('-create_at')
        context = {
            'blog' : blog,
            'last_blog' : last_blog[:3],
            'related_post' : last_blog.filter(category = blog.category),
            'category' : category,
            'tags' : tags
        }
        return render(request, 'blog-details.html', context)

templates/blogs.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- ==========Page Header Section Starts Here========== -->
    <div class="pageheader" style="background-image:url({% static "assets/images/bg/home1/4.png" %})">
        <div class="container">
            <div class="pageheader__content">
                <h2>Blogs</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Blogs</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- ==========Page Header Section Ends Here========== -->



    <!-- ===============>> Blog section start here <<================= -->
    <section class="blog blog--style1 padding-top padding-bottom" data-aos="fade-up" data-aos-duration="800">
        <div class="container">
            <div class="section-header text-center">
                <h2>Latest News, Blog & Articles</h2>
            </div>
            <div class="blog__wrapper">
                <div class="row g-4">
                    {% for blog in blog %}
                        <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-duration="700">
                            <div class="blog__item">
                                <div class="blog__item-inner">
                                    <div class="blog__thumb">
                                        {% if blog.photo1 %}
                                            <img src="{{ blog.photo1.url }}" alt="blog Images">
                                        {% endif %}
                                    </div>

                                    <div class="blog__content">
                                        <div class="blog__content-top">
                                            <span class="blog__meta-tag blog__meta-tag--cat{{ blog.style }}">{{ blog.category.name }}</span>
                                        </div>
                                        <h6> <a href="{% url "blog:blogs_detail" blog.id %}">{{ blog.title|slice:"0:50" }}</a> </h6>

                                        <div class="blog__content-bottom blog__content-bottom--border">
                                            <a href="#"><span><i class="fa-solid fa-calendar-days"></i></span>
                                                {{ blog.update_at }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    
                </div>
                <div class="paginations">
                    <ul class="lab-ul d-flex flex-wrap justify-content-center mb-1">
                        {% if mentors.has_previous %}
                            <li>
                                <a href="?page={{ mentors.previous_page_number }}"><i class="fa-solid fa-arrow-left"></i></a>
                            </li>
                        {% endif %}
                        
                        {% if mentors|length > 13 %}
                            <li>
                                <a href="#" class="active">{{ mentors.number }}</a>
                            </li>
                        {% endif %}
                        {% if mentors.has_next %}
                        <li>
                            <a href="?page={{ mentors.next_page_number }}"><i class="fa-solid fa-arrow-right"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- ===============>> Blog section end here <<================= -->








    <!-- ===============>> newsletter start here <<================= -->
    <div class="newsletter" data-aos="fade-up" data-aos-duration="800">
        <div class="container">
            <div class="newsletter__wrapper">
                <div class="newsletter__content">
                    <div class="newsletter__content-inner newsletter__content-inner--style1 text-center"
                        style="background-image:url({% static "assets/images/footer/2.png" %})">
                        <h2>Get free Pro memberships for
                            your high school class</h2>

                        <a href="{% url "accounts:signup" %}" class="trk-btn trk-btn--rounded trk-btn--primary1">Join With Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ===============>> newsletter end here <<================= -->


{% endblock content %} 

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- ==========Page Header Section Starts Here========== -->
    <div class="pageheader" style="background-image:url({% static "assets/images/bg/home1/7.png" %})">
        <div class="container">
            <div class="pageheader__content">
                <h2>Contact Us</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
     
    <!-- ==========Page Header Section Ends Here========== -->


    <!-- ==========cantact Section start Here========== -->
    <div class="conatct padding-top padding-bottom">
        <div class="container">
            <div class="contact__wrapper">
                <div class="row g-5">
                    <div class="col-lg-6" data-aos="fade-right" data-aos-duration="800">
                        <div class="cotact__details">
                            <div class="contact__header">
                                <h3>Always Here to Help you</h3>
                                <p>There are many variations of passages of Lorem Ipsum available, but the majority have
                                    suffered alteration in some form, by injected humor, or randomized words which don't
                                    look
                                    even slightly believable.</p>
                            </div>

                            <div class="contact__info">
                                <div class="contact__item">
                                    <div class="contact__item-thumb">
                                        <span><i class="fa-solid fa-location-dot"></i></span>
                                    </div>
                                    <div class="contact__item-content">
                                        <h5>Location</h5>
                                        <p class="mb-0">4517 Washington Ave. Manchester, Kentucky 39495</p>
                                    </div>
                                </div>
                                <div class="contact__item">
                                    <div class="contact__item-thumb">
                                        <span><i class="fa-solid fa-phone"></i></span>
                                    </div>
                                    <div class="contact__item-content">
                                        <h5>Contact</h5>
                                        <p class="mb-0">(405) 555-0128</p>
                                        <p class="mb-0">(603) 555-0123</p>
                                    </div>
                                </div>
                                <div class="contact__item">
                                    <div class="contact__item-thumb">
                                        <span><i class="fa-solid fa-envelope"></i></span>
                                    </div>
                                    <div class="contact__item-content">
                                        <h5>Email</h5>
                                        <p class="mb-0">nvt.isst.nute@gmail.com</p>
                                    </div>
                                </div>
                                <div class="contact__item">
                                    <div class="contact__item-thumb">
                                        <span><i class="fa-solid fa-clock"></i></span>
                                    </div>
                                    <div class="contact__item-content">
                                        <h5>Hours of operation</h5>
                                        <p class="mb-0">Monday - Friday: 09.00 - 20.00</p>
                                        <p class="mb-0">Sunday & Saturday: 10.30 - 22..30</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-lg-6" data-aos="fade-left" data-aos-duration="800">
                        <div class="contact__form">
                            <h3>Ready To Get Started?</h3>
                            <p>You email address will not be published. Required fields are marked.</p>
                            <!-- account form -->
                            <form method='post' class="account__form">{% csrf_token %}
                                <div class="row g-4">
                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            {{ form_class.full_name }}
                                            <div class="valid-tooltip">
                                                Looks good!
                                            </div>
                                            <div class="invalid-tooltip">
                                                Please enter a full name
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            {{ form_class.phone }}
                                            <div class="valid-tooltip">
                                                This mobile is valid
                                            </div>
                                            <div class="invalid-tooltip">
                                                Please enter a valid number
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            {{ form_class.body }}
                                        </div>
                                    </div>
                                </div>

                                

                                <button type="submit" class="trk-btn trk-btn--rounded trk-btn--secondary1 mt-3">Send
                                    Message</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ==========cantact Section Ends Here========== -->




    <!-- ==========location map start Here========== -->
    <div class="contact padding-bottom">
        <div class="container" data-aos="fade-up" data-aos-duration="800">
            <div class="contact__map">
                <div class="mapouter">
                    <div class="gmap_canvas"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2995.549654395407!2d69.28872207646297!3d41.340405198907405!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef3db2b06783b%3A0x84660e201e025d7a!2sICT%20ACADEMY!5e0!3m2!1sru!2s!4v1704799728729!5m2!1sru!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
                </div>
            </div>
        </div>
    </div>
    <!-- ==========location map end Here========== -->








    <!-- ===============>> newsletter start here <<================= -->
    <div class="newsletter" data-aos="fade-up" data-aos-duration="800">
        <div class="container">
            <div class="newsletter__wrapper">
                <div class="newsletter__content">
                    <div class="newsletter__content-inner newsletter__content-inner--style1 text-center"
                        style="background-image:url({% static "assets/images/footer/2.png" %})">
                        <h2>Get free Pro memberships for
                            your high school class</h2>

                        <a href="{% url "accounts:signup" %}" class="trk-btn trk-btn--rounded trk-btn--primary1">Join With Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ===============>> newsletter end here <<================= -->

{% endblock content %}

templates/signin.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!-- ==========Page Header Section Starts Here========== -->
    <div class="pageheader" style="background-image:url({% static "assets/images/bg/home1/9.png" %}">
        <div class="container">
            <div class="pageheader__content">
                <h2>Login</h2>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Login</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- ==========Page Header Section Ends Here========== -->



    <!-- ===============>> account start here <<================= -->
    <section class="account padding-top padding-bottom">
        <div class="container-fluid">
            <div class="account__wrapper" data-aos="fade-up" data-aos-duration="800">
                <div class="row g-4">
                    <div class="col-lg-12">
                        <div class="account__content">
                            <!-- account tittle -->
                            <div class="account__header">
                                <h3>Log in to your account</h3>
                                <p>Welcome back! Please enter your details.</p>
                            </div>
                            <!-- account form -->
                            <form method='post' class="account__form needs-validation" novalidate>{% csrf_token %}
                                <div class="row g-4">
                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            {{ login_form.username }}
                                            <div class="valid-tooltip">
                                                This email is valid
                                            </div>
                                            <div class="invalid-tooltip">
                                                Please enter a valid email
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="input-group">
                                            {{ login_form.password }}
                                            <div class="valid-tooltip">
                                                Looks good!
                                            </div>
                                            <div class="invalid-tooltip">
                                                Enter a strong password
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="account__form-passcheck">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" value="" id="terms-check">
                                        <label for="terms-check" class="form-check-label">
                                            Remember for 30 days
                                        </label>
                                    </div>
                                    <div class="account__form-forgotpass">
                                        <a href="forgot-pass.html">Forgot Password?</a>
                                    </div>
                                </div>

                                <button type="submit"
                                    class="trk-btn trk-btn--border trk-btn--secondary1 d-block mt-4">Sign in</button>
                            </form>
                            <!-- account social -->
                            <div class="account__social">
                                <a href="{% url 'social:begin' "google-oauth2" %}" class="account__social-btn"><span><img src="{% static "assets/images/others/google.svg" %}"
                                            alt="google icon"></span>
                                    Sign in with google
                                </a>
                            </div>

                            <div class="account__switch">
                                <p>Don't have an account? <a href="signup.html">Sign up</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ===============>> account end here <<================= -->

{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- ==========Page Header Section Starts Here========== -->
<div class="pageheader" style="background-image:url({% static "assets/images/bg/home1/10.png" %})">
    <div class="container">
        <div class="pageheader__content">
            <h2>Sign Up</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url "home:home" %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Sign Up</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- ==========Page Header Section Ends Here========== -->

{% if messages %}
    <div class="container mt-4">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
            {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                {% endif %}
                    {{ message }}
                </div>
        {% endfor %}
    </div>

{% endif %}



<!-- ===============>> account start here <<================= -->
<section class="account padding-top padding-bottom">
    <div class="container-fluid">
        <div class="account__wrapper" data-aos="fade-up" data-aos-duration="800">
            <div class="row g-4">
                <div class="col-lg-12">
                    <div class="account__content">
                        <!-- account tittle -->
                        <div class="account__header">
                         
                            <h3>Create an account</h3>
                        </div>
                        <!-- account form -->
                        <form method='post' class="account__form">{% csrf_token %}
                            <div class="row g-4">
                                <div class="col-lg-12">
                                    <div class="input-group">
                                        {{ form.username }}
                                        <div class="valid-tooltip">
                                            Looks good!
                                        </div>
                                        <div class="invalid-tooltip">
                                            Please enter a username
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="input-group">
                                        {{ form.phone }}

                                        <div class="valid-tooltip">
                                            This mobile is valid
                                        </div>
                                        <div class="invalid-tooltip">
                                            Please enter a valid number
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-12">
                                    <div class="input-group">
                                        <!-- <span class="input-group-icon"><i
                                                class="fa-solid fa-eye"></i></span> -->
                                                {{ form.password }}

                                        <div class="valid-tooltip">
                                            Looks good!
                                        </div>
                                        <div class="invalid-tooltip">
                                            Enter a strong password
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-12">
                                    <div class="input-group">
                                        <!-- <span class="input-group-icon"><i
                                                class="fa-solid fa-eye"></i></span> -->
                                                {{ form.confirm_password }}

                                        <div class="valid-tooltip">
                                            Looks good!
                                        </div>
                                        <div class="invalid-tooltip">
                                            Enter a strong confirm password
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="account__form-passcheck">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" value="" id="terms-check">
                                    <label for="terms-check" class="form-check-label">
                                        Agree to our <a href="#"> terms & conditions</a>
                                    </label>
                                </div>
                                <!-- <div class="account__form-forgotpass">
                                    <a href="#">Forgot Password?</a>
                                </div> -->
                            </div>

                            <button type="submit"
                                class="trk-btn trk-btn--border trk-btn--secondary1 d-block mt-4">Sign Up</button>
                        </form>
                        <!-- account social -->
                        <div class="account__social">
                            <a href="{% url 'social:begin' "google-oauth2" %}" class="account__social-btn"><span><img src="{% static "assets/images/others/google.svg" %}"
                                        alt="google icon"></span>
                                Sign in with google
                            </a>
                        </div>

                        <div class="account__switch">
                            <p>Already have an account? <a href="{% url "accounts:signin" %}">Log in</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ===============>> account end here <<================= -->

{% endblock content %}